const obj=[
    {
        weight: [Object],
        height: [Object],
        id: 24,
        name: 'Australian Terrier',
        country_code: 'AU',
        bred_for: 'Cattle herdering, hunting snakes and rodents',
        breed_group: 'Terrier',
        life_span: '15 years',
        temperament: 'Spirited, Alert, Loyal, Companionable, Even Tempered, Courageous',
        reference_image_id: 'r1Ylge5Vm',
        image: [Object]
      },
      {
        weight: [Object],
        height: [Object],
        id: 25,
        name: 'Azawakh',
        bred_for: 'Livestock guardian, hunting',
        breed_group: 'Hound',
        life_span: '10 - 13 years',
        temperament: 'Aloof, Affectionate, Attentive, Rugged, Fierce, Refined',
        reference_image_id: 'SkvZgx94m',
        image: [Object]
      },
      {
        weight: [Object],
        height: [Object],
        id: 26,
        name: 'Barbet',
        bred_for: 'Hunting water game',
        life_span: '13 – 15 years',
        temperament: 'Obedient, Companionable, Intelligent, Joyful',
        reference_image_id: 'HyWGexcVQ',
        image: [Object]
      },
      {
        weight: [Object],
        height: [Object],
        id: 28,
        name: 'Basenji',
        bred_for: 'Hunting',
        breed_group: 'Hound',
        life_span: '10 - 12 years',
        temperament: 'Affectionate, Energetic, Alert, Curious, Playful, Intelligent',
        reference_image_id: 'H1dGlxqNQ',
        image: [Object]
      },
      {
        weight: [Object],
        height: [Object],
        id: 29,
        name: 'Basset Bleu de Gascogne',
        bred_for: 'Hunting on foot.',
        breed_group: 'Hound',
        life_span: '10 - 14 years',
        temperament: 'Affectionate, Lively, Agile, Curious, Happy, Active',    
        reference_image_id: 'BkMQll94X',
        image: [Object]
      },
      {
        weight: [Object],
        height: [Object],
        id: 30,
        name: 'Basset Hound',
        bred_for: 'Hunting by scent',
        breed_group: 'Hound',
        life_span: '12 - 15 years',
        temperament: 'Tenacious, Friendly, Affectionate, Devoted, Sweet-Tempered, Gentle',
        reference_image_id: 'Sy57xx9EX',
        image: [Object]
      },
      {
        weight: [Object],
        height: [Object],
        id: 31,
        name: 'Beagle',
        bred_for: 'Rabbit, hare hunting',
        breed_group: 'Hound',
        life_span: '13 - 16 years',
        temperament: 'Amiable, Even Tempered, Excitable, Determined, Gentle, Intelligent',
        reference_image_id: 'Syd4xxqEm',
        image: [Object]
      },
      {
        weight: [Object],
        height: [Object],
        id: 32,
        name: 'Bearded Collie',
        bred_for: 'Sheep herding',
        breed_group: 'Herding',
        life_span: '12 - 14 years',
        temperament: 'Self-confidence, Hardy, Lively, Alert, Intelligent, Active',
        reference_image_id: 'A09F4c1qP',
        image: [Object]
      },
      {
        weight: [Object],
        height: [Object],
        id: 33,
        name: 'Beauceron',
        bred_for: 'Boar herding, hunting, guarding',
        breed_group: 'Herding',
        life_span: '10 - 12 years',
        temperament: 'Fearless, Friendly, Intelligent, Protective, Calm',      
        reference_image_id: 'HJQ8ge5V7',
        image: [Object]
      },
      {
        weight: [Object],
        height: [Object],
        id: 34,
        name: 'Bedlington Terrier',
        bred_for: 'Killing rat, badger, other vermin',
        breed_group: 'Terrier',
        life_span: '14 - 16 years',
        temperament: 'Affectionate, Spirited, Intelligent, Good-tempered',     
        reference_image_id: 'ByK8gx947',
        image: [Object]
      },
      {
        weight: [Object],
        height: [Object],
        id: 36,
        name: 'Belgian Malinois',
        bred_for: 'Stock herding',
        breed_group: 'Herding',
        life_span: '12 - 14 years',
        temperament: 'Watchful, Alert, Stubborn, Friendly, Confident, Hard-working, Active, Protective',
        reference_image_id: 'r1f_ll5VX',
        image: [Object]
      },
      {
        weight: [Object],
        height: [Object],
        id: 38,
        name: 'Belgian Tervuren',
        bred_for: 'Guarding, Drafting, Police work.',
        breed_group: 'Herding',
        life_span: '10 - 12 years',
        temperament: 'Energetic, Alert, Loyal, Intelligent, Attentive, Protective',
        reference_image_id: 'B1KdxlcNX',
        image: [Object]
      },
      {
        weight: [Object],
        height: [Object],
        id: 41,
        name: 'Bernese Mountain Dog',
        bred_for: 'Draft work',
        breed_group: 'Working',
        life_span: '7 - 10 years',
        temperament: 'Affectionate, Loyal, Intelligent, Faithful',
        reference_image_id: 'S1fFlx5Em',
        image: [Object]
      },
      {
        weight: [Object],
        height: [Object],
        id: 42,
        name: 'Bichon Frise',
        bred_for: 'Companion',
        breed_group: 'Non-Sporting',
        life_span: '15 years',
        temperament: 'Feisty, Affectionate, Cheerful, Playful, Gentle, Sensitive',
        reference_image_id: 'HkuYlxqEQ',
        image: [Object]
      },
      {
        weight: [Object],
        height: [Object],
        id: 43,
        name: 'Black and Tan Coonhound',
        bred_for: 'Hunting raccoons, night hunting',
        breed_group: 'Hound',
        life_span: '10 - 12 years',
        temperament: 'Easygoing, Gentle, Adaptable, Trusting, Even Tempered, Lovable',
        reference_image_id: 'HJAFgxcNQ',
        image: [Object]
      },
      {
        weight: [Object],
        height: [Object],
        id: 45,
        name: 'Bloodhound',
        bred_for: 'Trailing',
        breed_group: 'Hound',
        life_span: '8 - 10 years',
        temperament: 'Stubborn, Affectionate, Gentle, Even Tempered',
        reference_image_id: 'Skdcgx9VX',
        image: [Object]
      },
      {
        weight: [Object],
        height: [Object],
        id: 47,
        name: 'Bluetick Coonhound',
        bred_for: 'Hunting with a superior sense of smell.',
        breed_group: 'Hound',
        life_span: '12 - 14 years',
        temperament: 'Friendly, Intelligent, Active',
        reference_image_id: 'rJxieg9VQ',
        image: [Object]
      },
      {
        weight: [Object],
        height: [Object],
        id: 48,
        name: 'Boerboel',
        bred_for: 'Guarding the homestead, farm work.',
        breed_group: 'Working',
        life_span: '10 - 12 years',
        temperament: 'Obedient, Confident, Intelligent, Dominant, Territorial',
        reference_image_id: 'HyOjge5Vm',
        image: [Object]
      },
      {
        weight: [Object],
        height: [Object],
        id: 50,
        name: 'Border Collie',
        bred_for: 'Sheep herder',
        breed_group: 'Herding',
        life_span: '12 - 16 years',
        temperament: 'Tenacious, Keen, Energetic, Responsive, Alert, Intelligent',
        reference_image_id: 'sGQvQUpsp',
        image: [Object]
      },
      {
        weight: [Object],
        height: [Object],
        id: 51,
        name: 'Border Terrier',
        bred_for: 'Fox bolting, ratting',
        breed_group: 'Terrier',
        life_span: '12 - 14 years',
        temperament: 'Fearless, Affectionate, Alert, Obedient, Intelligent, Even Tempered',
        reference_image_id: 'HJOpge9Em',
        image: [Object]
      },
      {
        weight: [Object],
        height: [Object],
        id: 53,
        name: 'Boston Terrier',
        bred_for: 'Ratting, Companionship',
        breed_group: 'Non-Sporting',
        life_span: '11 - 13 years',
        temperament: 'Friendly, Lively, Intelligent',
        reference_image_id: 'rkZRggqVX',
        image: [Object]
      },
      {
        weight: [Object],
        height: [Object],
        id: 54,
        name: 'Bouvier des Flandres',
        bred_for: 'Cattle herding',
        breed_group: 'Herding',
        life_span: '10 - 15 years',
        temperament: 'Protective, Loyal, Gentle, Intelligent, Familial, Rational',
        reference_image_id: 'Byd0xl5VX',
        image: [Object]
      },
      {
        weight: [Object],
        height: [Object],
        id: 55,
        name: 'Boxer',
        bred_for: 'Bull-baiting, guardian',
        breed_group: 'Working',
        life_span: '8 - 10 years',
        temperament: 'Devoted, Fearless, Friendly, Cheerful, Energetic, Loyal, Playful, Confident, Intelligent, Bright, Brave, Calm',
        reference_image_id: 'ry1kWe5VQ',
        image: [Object]
      },
      {
        weight: [Object],
        height: [Object],
        id: 56,
        name: 'Boykin Spaniel',
        bred_for: 'Turkey retrieving',
        breed_group: 'Sporting',
        life_span: '10 - 14 years',
        temperament: 'Friendly, Energetic, Companionable, Intelligent, Eager, Trainable',
        reference_image_id: 'ryHJZlcNX',
        image: [Object]
      },
      {
        weight: [Object],
        height: [Object],
        id: 57,
        name: 'Bracco Italiano',
        bred_for: 'Versatile gun dog',
        breed_group: 'Sporting',
        life_span: '10 - 12 years',
        temperament: 'Stubborn, Affectionate, Loyal, Playful, Companionable, Trainable',
        reference_image_id: 'S13yZg5VQ',
        image: [Object]
      },
      {
        weight: [Object],
        height: [Object],
        id: 58,
        name: 'Briard',
        bred_for: 'Herding, guarding sheep',
        breed_group: 'Herding',
        life_span: '10 - 12 years',
        temperament: 'Fearless, Loyal, Obedient, Intelligent, Faithful, Protective',
        reference_image_id: 'rkVlblcEQ',
        image: [Object]
      },
      {
        weight: [Object],
        height: [Object],
        id: 59,
        name: 'Brittany',
        bred_for: 'Pointing, retrieving',
        breed_group: 'Sporting',
        life_span: '12 - 14 years',
        temperament: 'Agile, Adaptable, Quick, Intelligent, Attentive, Happy', 
        reference_image_id: 'HJWZZxc4X',
        image: [Object]
      },
      {
        weight: [Object],
        height: [Object],
        id: 61,
        name: 'Bull Terrier',
        bred_for: 'Bull baiting, Fighting',
        breed_group: 'Terrier',
        life_span: '10 - 12 years',
        temperament: 'Trainable, Protective, Sweet-Tempered, Keen, Active',    
        reference_image_id: 'VSraIEQGd',
        image: [Object]
      },
      {
        weight: [Object],
        height: [Object],
        id: 62,
        name: 'Bull Terrier (Miniature)',
        bred_for: "An elegant man's fashion statement",
        life_span: '11 – 14 years',
        temperament: 'Trainable, Protective, Sweet-Tempered, Keen, Active, Territorial',
        reference_image_id: 'BkKZWlcVX',
        image: [Object]
      },
      {
        weight: [Object],
        height: [Object],
        id: 64,
        name: 'Bullmastiff',
        bred_for: 'Estate guardian',
        breed_group: 'Working',
        life_span: '8 - 12 years',
        temperament: 'Docile, Reliable, Devoted, Alert, Loyal, Reserved, Loving, Protective, Powerful, Calm, Courageous',
        reference_image_id: 'r1ifZl5E7',
        image: [Object]
      },
      {
        weight: [Object],
        height: [Object],
        id: 65,
        name: 'Cairn Terrier',
        bred_for: 'Bolting of otter, foxes, other vermin',
        breed_group: 'Terrier',
        life_span: '14 - 15 years',
        temperament: 'Hardy, Fearless, Assertive, Gay, Intelligent, Active',   
        reference_image_id: 'Sk7Qbg9E7',
        image: [Object]
      },
      {
        weight: [Object],
        height: [Object],
        id: 67,
        name: 'Cane Corso',
        bred_for: 'Companion, guard dog, and hunter',
        breed_group: 'Working',
        life_span: '10 - 11 years',
        temperament: 'Trainable, Reserved, Stable, Quiet, Even Tempered, Calm',
        reference_image_id: 'r15m-lc4m',
        image: [Object]
      },
      {
        weight: [Object],
        height: [Object],
        id: 68,
        name: 'Cardigan Welsh Corgi',
        bred_for: 'Cattle droving',
        breed_group: 'Herding',
        life_span: '12 - 14 years',
        temperament: 'Affectionate, Devoted, Alert, Companionable, Intelligent, Active',
        reference_image_id: 'SyXN-e9NX',
        image: [Object]
      },
      {
        weight: [Object],
        height: [Object],
        id: 69,
        name: 'Catahoula Leopard Dog',
        bred_for: 'Driving livestock',
        breed_group: 'Herding',
        life_span: '10 - 12 years',
        temperament: 'Energetic, Inquisitive, Independent, Gentle, Intelligent, Loving',
        reference_image_id: 'BJcNbec4X',
        image: [Object]
      },
      {
        weight: [Object],
        height: [Object],
        id: 70,
        name: 'Caucasian Shepherd (Ovcharka)',
        bred_for: 'Guard dogs, defending sheep from predators, mainly wolves, jackals and bears',
        breed_group: 'Working',
        life_span: '10 - 12 years',
        temperament: 'Alert, Quick, Dominant, Powerful, Calm, Strong',
        reference_image_id: 'r1rrWe5Em',
        image: [Object]
      },
      {
        weight: [Object],
        height: [Object],
        id: 71,
        name: 'Cavalier King Charles Spaniel',
        bred_for: 'Flushing small birds, companion',
        breed_group: 'Toy',
        life_span: '10 - 14 years',
        temperament: 'Fearless, Affectionate, Sociable, Patient, Playful, Adaptable',
        reference_image_id: 'HJRBbe94Q',
        image: [Object]
      },
      {
        weight: [Object],
        height: [Object],
        id: 76,
        name: 'Chesapeake Bay Retriever',
        bred_for: 'Water Retriever',
        breed_group: 'Sporting',
        life_span: '10 - 13 years',
        temperament: 'Affectionate, Intelligent, Quiet, Dominant, Happy, Protective',
        reference_image_id: '9BXwUeCc2',
        image: [Object]
      },
      {
        weight: [Object],
        height: [Object],
        id: 78,
        name: 'Chinese Crested',
        bred_for: 'Ratting, lapdog, curio',
        breed_group: 'Toy',
        life_span: '10 - 14 years',
        temperament: 'Affectionate, Sweet-Tempered, Lively, Alert, Playful, Happy',
        reference_image_id: 'B1pDZx9Nm',
        image: [Object]
      },
      {
        weight: [Object],
        height: [Object],
        id: 79,
        name: 'Chinese Shar-Pei',
        bred_for: 'Fighting',
        breed_group: 'Non-Sporting',
        life_span: '10 years',
        temperament: 'Suspicious, Affectionate, Devoted, Reserved, Independent, Loving',
        reference_image_id: 'B1ruWl94Q',
        image: [Object]
      },
      {
        weight: [Object],
        height: [Object],
        id: 80,
        name: 'Chinook',
        bred_for: 'Sled pulling',
        breed_group: 'Working',
        life_span: '12 - 15 years',
        temperament: 'Friendly, Alert, Dignified, Intelligent, Calm',
        reference_image_id: 'Sypubg54Q',
        image: [Object]
      },
      {
        weight: [Object],
        height: [Object],
        id: 81,
        name: 'Chow Chow',
        bred_for: 'Guardian, cart pulling, hunting',
        breed_group: 'Non-Sporting',
        life_span: '12 - 15 years',
        temperament: 'Aloof, Loyal, Independent, Quiet',
        reference_image_id: 'ry8KWgqEQ',
        image: [Object]
      },
      {
        weight: [Object],
        height: [Object],
        id: 84,
        name: 'Clumber Spaniel',
        bred_for: 'Bird flushing, retrieving',
        breed_group: 'Sporting',
        life_span: '10 - 12 years',
        temperament: 'Affectionate, Loyal, Dignified, Gentle, Calm, Great-hearted',
        reference_image_id: 'rkeqWgq4Q',
        image: [Object]
      },
      {
        weight: [Object],
        height: [Object],
        id: 86,
        name: 'Cocker Spaniel',
        bred_for: 'Bird flushing, retrieving',
        breed_group: 'Sporting',
        life_span: '12 - 15 years',
        temperament: 'Trainable, Friendly, Affectionate, Playful, Quiet, Faithful',
        reference_image_id: '1lFmrzECl',
        image: [Object]
      },
      {
        weight: [Object],
        height: [Object],
        id: 87,
        name: 'Cocker Spaniel (American)',
        bred_for: 'Hunting the American woodcock',
        breed_group: 'Sporting',
        life_span: '12 - 15 years',
        temperament: 'Outgoing, Sociable, Trusting, Joyful, Even Tempered, Merry',
        reference_image_id: 'HkRcZe547',
        image: [Object]
      },
      {
        weight: [Object],
        height: [Object],
        id: 89,
        name: 'Coton de Tulear',
        bred_for: 'Accompanying ladies on long sea voyages, ratters onboard ship.',
        breed_group: 'Non-Sporting',
        life_span: '13 - 16 years',
        temperament: 'Affectionate, Lively, Playful, Intelligent, Trainable, Vocal',
        reference_image_id: 'SyviZlqNm',
        image: [Object]
      },
      {
        weight: [Object],
        height: [Object],
        id: 92,
        name: 'Dalmatian',
        bred_for: 'Carriage dog - trot alongside carriages to protect the occupants from banditry or other interference',
        breed_group: 'Non-Sporting',
        life_span: '10 - 13 years',
        temperament: 'Outgoing, Friendly, Energetic, Playful, Sensitive, Intelligent, Active',
        reference_image_id: 'SkJ3blcN7',
        image: [Object]
      },
      {
        weight: [Object],
        height: [Object],
        id: 94,
        name: 'Doberman Pinscher',
        bred_for: 'Guardian',
        breed_group: 'Working',
        life_span: '10 years',
        temperament: 'Fearless, Energetic, Alert, Loyal, Obedient, Confident, Intelligent',
        reference_image_id: 'HyL3bl94Q',
        image: [Object]
      },
      {
        weight: [Object],
        height: [Object],
        id: 95,
        name: 'Dogo Argentino',
        bred_for: 'Big-game hunting',
        breed_group: 'Working',
        life_span: '10 - 12 years',
        temperament: 'Friendly, Affectionate, Cheerful, Loyal, Tolerant, Protective',
        reference_image_id: 'S1nhWx94Q',
        image: [Object]
      },
      {
        weight: [Object],
        height: [Object],
        id: 98,
        name: 'Dutch Shepherd',
        bred_for: 'Farms, watchdog, guard duty',
        life_span: '15 years',
        temperament: 'Reliable, Affectionate, Alert, Loyal, Obedient, Trainable',
        reference_image_id: 'BkE6Wg5E7',
        image: [Object]
      },
      {
        weight: [Object],
        height: [Object],
        id: 101,
        name: 'English Setter',
        bred_for: 'Bird setting, retrieving',
        breed_group: 'Sporting',
        life_span: '12 years',
        temperament: 'Strong Willed, Mischievous, Affectionate, Energetic, Playful, Companionable, Gentle, Hard-working, Intelligent, Eager, People-Oriented',
        reference_image_id: 'By4A-eqVX',
        image: [Object]
      },
      {
        weight: [Object],
        height: [Object],
        id: 102,
        name: 'English Shepherd',
        bred_for: 'Herding & guarding livestock, farm watch dog',
        breed_group: 'Working',
        life_span: '10 - 13 years',
        temperament: 'Kind, Energetic, Independent, Adaptable, Intelligent, Bossy',
        reference_image_id: 'H1QyMe5EQ',
        image: [Object]
      },
      {
        weight: [Object],
        height: [Object],
        id: 103,
        name: 'English Springer Spaniel',
        bred_for: 'Bird flushing, retrieving',
        breed_group: 'Sporting',
        life_span: '12 - 14 years',
        temperament: 'Affectionate, Cheerful, Alert, Intelligent, Attentive, Active',
        reference_image_id: 'Hk0Jfe5VQ',
        image: [Object]
      },
      {
        weight: [Object],
        height: [Object],
        id: 104,
        name: 'English Toy Spaniel',
        bred_for: 'Companion of kings',
        breed_group: 'Toy',
        life_span: '10 - 12 years',
        temperament: 'Affectionate, Reserved, Playful, Gentle, Happy, Loving', 
        reference_image_id: 'SkIgzxqNQ',
        image: [Object]
      },
      {
        weight: [Object],
        height: [Object],
        id: 105,
        name: 'English Toy Terrier',
        bred_for: 'Rat-baiting',
        life_span: '12 - 13 years',
        temperament: 'Stubborn, Alert, Companionable, Intelligent, Cunning, Trainable',
        reference_image_id: 'SJ6eMxqEQ',
        image: [Object]
      },
      {
        weight: [Object],
        height: [Object],
        id: 107,
        name: 'Eurasier',
        bred_for: 'Companionship',
        breed_group: 'Non-Sporting',
        life_span: '12 - 14 years',
        temperament: 'Alert, Reserved, Intelligent, Even Tempered, Watchful, Calm',
        reference_image_id: 'S1VWGx9Nm',
        image: [Object]
      },
      {
        weight: [Object],
        height: [Object],
        id: 108,
        name: 'Field Spaniel',
        bred_for: 'Bird flushing, retrieving',
        breed_group: 'Sporting',
        life_span: '11 - 15 years',
        temperament: 'Docile, Cautious, Sociable, Sensitive, Adaptable, Familial',
        reference_image_id: 'SkJfGecE7',
        image: [Object]
      },
      {
        weight: [Object],
        height: [Object],
        id: 110,
        name: 'Finnish Lapphund',
        bred_for: 'Herding reindeer',
        breed_group: 'Herding',
        life_span: '12 - 15 years',
        temperament: 'Friendly, Keen, Faithful, Calm, Courageous',
        reference_image_id: 'S1KMGg5Vm',
        image: [Object]
      },
      {
        weight: [Object],
        height: [Object],
        id: 111,
        name: 'Finnish Spitz',
        bred_for: 'Hunting birds, small mammals',
        breed_group: 'Non-Sporting',
        life_span: '12 - 15 years',
        temperament: 'Playful, Loyal, Independent, Intelligent, Happy, Vocal', 
        reference_image_id: '3PjHlQbkV',
        image: [Object]
      },
      {
        weight: [Object],
        height: [Object],
        id: 113,
        name: 'French Bulldog',
        bred_for: 'Lapdog',
        breed_group: 'Non-Sporting',
        life_span: '9 - 11 years',
        temperament: 'Playful, Affectionate, Keen, Sociable, Lively, Alert, Easygoing, Patient, Athletic, Bright',
        reference_image_id: 'HyWNfxc47',
        image: [Object]
      },
      {
        weight: [Object],
        height: [Object],
        id: 114,
        name: 'German Pinscher',
        bred_for: 'Watchdog, Hunting vermin on the farm.',
        breed_group: 'Working',
        life_span: '12 - 14 years',
        temperament: 'Spirited, Lively, Intelligent, Loving, Even Tempered, Familial',
        reference_image_id: 'B1u4zgqE7',
        image: [Object]
      },
      {
        weight: [Object],
        height: [Object],
        id: 115,
        name: 'German Shepherd Dog',
        bred_for: 'Herding, Guard dog',
        breed_group: 'Herding',
        life_span: '10 - 13 years',
        temperament: 'Alert, Loyal, Obedient, Curious, Confident, Intelligent, Watchful, Courageous',
        reference_image_id: 'SJyBfg5NX',
        image: [Object]
      },
      {
        weight: [Object],
        height: [Object],
        id: 116,
        name: 'German Shorthaired Pointer',
        bred_for: 'General hunting',
        breed_group: 'Sporting',
        life_span: '12 - 14 years',
        temperament: 'Boisterous, Bold, Affectionate, Intelligent, Cooperative, Trainable',
        reference_image_id: 'SJqBMg5Nm',
        image: [Object]
      },
      {
        weight: [Object],
        height: [Object],
        id: 119,
        name: 'Giant Schnauzer',
        bred_for: 'Herding, guarding',
        breed_group: 'Working',
        life_span: '10 - 12 years',
        temperament: 'Strong Willed, Kind, Loyal, Intelligent, Dominant, Powerful',
        reference_image_id: 'H1NIzlcV7',
        image: [Object]
      },
      {
        weight: [Object],
        height: [Object],
        id: 120,
        name: 'Glen of Imaal Terrier',
        bred_for: 'Rid the home and farm of vermin, and hunt badger and fox',  
        breed_group: 'Terrier',
        life_span: '12 - 15 years',
        temperament: 'Spirited, Agile, Loyal, Gentle, Active, Courageous',     
        reference_image_id: 'H1oLMe94m',
        image: [Object]
      },
      {
        weight: [Object],
        height: [Object],
        id: 121,
        name: 'Golden Retriever',
        bred_for: 'Retrieving',
        breed_group: 'Sporting',
        life_span: '10 - 12 years',
        temperament: 'Intelligent, Kind, Reliable, Friendly, Trustworthy, Confident',
        reference_image_id: 'HJ7Pzg5EQ',
        image: [Object]
      },
      {
        weight: [Object],
        height: [Object],
        id: 123,
        name: 'Gordon Setter',
        bred_for: 'Find and point gamebirds',
        breed_group: 'Sporting',
        life_span: '10 - 12 years',
        temperament: 'Fearless, Alert, Loyal, Confident, Gay, Eager',
        reference_image_id: 'SJ5vzx5NX',
        image: [Object]
      },
      {
        weight: [Object],
        height: [Object],
        id: 124,
        name: 'Great Dane',
        bred_for: 'Hunting & holding boars, Guardian',
        breed_group: 'Working',
        life_span: '7 - 10 years',
        temperament: 'Friendly, Devoted, Reserved, Gentle, Confident, Loving', 
        reference_image_id: 'B1Edfl9NX',
        image: [Object]
      },
      {
        weight: [Object],
        height: [Object],
        id: 125,
        name: 'Great Pyrenees',
        bred_for: 'Sheep guardian',
        breed_group: 'Working',
        life_span: '10 - 12 years',
        temperament: 'Strong Willed, Fearless, Affectionate, Patient, Gentle, Confident',
        reference_image_id: 'B12uzg9V7',
        image: [Object]
      },
      {
        weight: [Object],
        height: [Object],
        id: 127,
        name: 'Greyhound',
        bred_for: 'Coursing hares',
        breed_group: 'Hound',
        life_span: '10 - 13 years',
        temperament: 'Affectionate, Athletic, Gentle, Intelligent, Quiet, Even Tempered',
        reference_image_id: 'ryNYMx94X',
        image: [Object]
      },
      {
        weight: [Object],
        height: [Object],
        id: 128,
        name: 'Griffon Bruxellois',
        bred_for: 'Hunt and kill vermin in stables',
        life_span: '10 – 15 years',
        temperament: 'Self-important, Inquisitive, Alert, Companionable, Sensitive, Watchful',
        reference_image_id: 'ryoYGec4Q',
        image: [Object]
      },
      {
        weight: [Object],
        height: [Object],
        id: 129,
        name: 'Harrier',
        bred_for: 'Hunting hares by trailing them',
        breed_group: 'Hound',
        life_span: '12 - 15 years',
        temperament: 'Outgoing, Friendly, Cheerful, Sweet-Tempered, Tolerant, Active',
        reference_image_id: 'B1IcfgqE7',
        image: [Object]
      },
      {
        weight: [Object],
        height: [Object],
        id: 130,
        name: 'Havanese',
        bred_for: 'Companionship',
        breed_group: 'Toy',
        life_span: '14 - 15 years',
        temperament: 'Affectionate, Responsive, Playful, Companionable, Gentle, Intelligent',
        reference_image_id: 'rkXiGl9V7',
        image: [Object]
      },
      {
        weight: [Object],
        height: [Object],
        id: 134,
        name: 'Irish Setter',
        bred_for: 'Bird setting, retrieving',
        breed_group: 'Sporting',
        life_span: '10 - 11 years',
        temperament: 'Affectionate, Energetic, Lively, Independent, Playful, Companionable',
        reference_image_id: 'S1osGeqVm',
        image: [Object]
      },
      {
        weight: [Object],
        height: [Object],
        id: 135,
        name: 'Irish Terrier',
        breed_group: 'Terrier',
        life_span: '12 - 16 years',
        temperament: 'Respectful, Lively, Intelligent, Dominant, Protective, Trainable',
        reference_image_id: 'By-hGecVX',
        image: [Object]
      },
      {
        weight: [Object],
        height: [Object],
        id: 137,
        name: 'Irish Wolfhound',
        bred_for: 'Coursing wolves, elk',
        breed_group: 'Hound',
        life_span: '6 - 8 years',
        temperament: 'Sweet-Tempered, Loyal, Dignified, Patient, Thoughtful, Generous',
        reference_image_id: 'Hyd2zgcEX',
        image: [Object]
      },
      {
        weight: [Object],
        height: [Object],
        id: 138,
        name: 'Italian Greyhound',
        bred_for: 'Lapdog',
        breed_group: 'Toy',
        life_span: '12 - 15 years',
        temperament: 'Mischievous, Affectionate, Agile, Athletic, Companionable, Intelligent',
        reference_image_id: 'SJAnzg9NX',
        image: [Object]
      },
      {
        weight: [Object],
        height: [Object],
        id: 140,
        image: [Object]
      },
]
console.log(obj[0].temperament)